name: QA Portfolio CI

on:
  push:
    branches: [main,master]
  pull_request:
    branches: [main,master]
  workflow_dispatch: # 允许手动触发

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run API tests with Allure results
        run: |
          pytest api_tests/ -v --env=prod --alluredir=./allure-results
        continue-on-error: true # 即使有失败用例也继续生成报告

      - name: Load test report history
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Build Allure report
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: ./allure-results
          allure_history: gh-pages/allure-history
          keep_reports: 20 # 保留最近20次构建历史

      - name: Setup Pages
        uses: actions/configure-pages@v4
        if: always()

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        if: always()
        with:
          path: gh-pages/allure-history  # 注意路径

    deploy:
      needs: test
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      runs-on: ubuntu-latest
      environment:
        name: github-pages
        url: ${{ steps.deployment.outputs.page_url }}
      steps:
        - name: Deploy to GitHub Pages
          id: deployment
          uses: actions/deploy-pages@v4
